### ISSUE TITLE
Error Creating Config File

### ISSUE THREAD

**Issue by RealDotNetDave** [korzh/aistdoc#22]
I installed aistdoc and tried to create the config file and I am getting this error:

c:\Temp>aistdoc --create:cs:dotnettips
aistdoc utility 2.0.3.1 (c) Aistant 2018-2019
Current folder: c:\Temp
Specify --help for a list of available options and commands.

Unhandled Exception: McMaster.Extensions.CommandLineUtils.UnrecognizedCommandParsingException: Unrecognized option '--create:cs:dotnettips'
   at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.HandleUnexpectedArg(String argTypeName, String argValue)
   at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.ProcessOption(OptionArgument arg)
   at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.ProcessNext()
   at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.Process()
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Parse(String[] args)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at aistdoc.Program.Main(String[] args) in C:\azuredevops-agents\korzhdev\_work\19\s\src\aistdoc\Program.cs:line 20

c:\Temp>

**Comment by antifree** [comment]
Hello, we have changed commands in version 2.0.0, but forgot to update our documentation.

You can see all up-to-date commands using `help` command.

```
aistdoc --help
```

```
Usage: aistdoc [options] [command]

Options:
  -?|-h|--help  Show help information

Commands:
  changelog     Creates release notes for new version tag from repository
  create        Creates configuration file
  publish       Publish documentation

Run 'aistdoc [command] --help' for more information about a command.
```

```
aistdoc create --help
```

```
Usage: aistdoc create [options]

Options:
  -?|-h|--help            Show help information
  -f|--file[:<filename>]  New config file name
  -m|--mode[:<mode>]      The mode. cs ot ts
```

So, in your case you should use in such a way:

```
aistdoc create -f:dotnettips -m:cs
```
